/* CompX Style Director - reference-driven, local-first AE style system. */
(function () {
  "use strict";
  var root = document.getElementById("moodboardWorkspace");
  if (!root) return;
  var bridge = window.CompXHostBridge;
  var cs = window.csInterface || (typeof CSInterface !== "undefined" ? new CSInterface() : null);
  var fs = null, path = null, docsPath = "";
  try { fs = window.require ? window.require("fs") : require("fs"); path = window.require ? window.require("path") : require("path"); } catch (e) { console.warn("Style Director storage unavailable", e); }
  try { docsPath = cs ? cs.getSystemPath(SystemPath.MY_DOCUMENTS) : ""; } catch (e2) { console.warn("Style Director Documents path unavailable", e2); }
  var storageRoot = fs && path && docsPath ? path.join(docsPath, "CompX", "Moodboards") : "";
  var indexPath = storageRoot ? path.join(storageRoot, "boards.json") : "";
  var state = { schema: 2, activeBoardId: "", boards: [] };
  var activeReferenceId = "", roleFilter = "all";
  var el = {};
  ["mbBoardSelect","mbNewBoard","mbRenameBoard","mbDeleteBoard","mbRevealFolder","mbDropzone","mbReferenceInput","mbBrowseReferences","mbCaptureComp","mbAddLink","mbAddNote","mbTagList","mbRoleFilter","mbReferenceGrid","mbReferenceCount","mbEmptyState","mbAnalyze","mbStyleDna","mbPalette","mbSemanticPalette","mbTypography","mbMotion","mbEditing","mbContrast","mbTemperature","mbSaturation","mbGrain","mbGenerateKit","mbApplyStyle","mbRestoreStyle","mbMatchLook","mbLinkedStyle","mbLookIntensity","mbLookIntensityValue","mbScanStyle","mbFixStyle","mbHealthScore","mbHealthSummary","mbStatus"].forEach(function (id) { el[id] = document.getElementById(id); });
  function uid(prefix) { return (prefix || "sd") + "_" + Date.now().toString(36) + "_" + Math.random().toString(36).slice(2, 9); }
  function cleanName(v) { return String(v || "").replace(/[\\/:*?"<>|\x00-\x1f]/g, "_").replace(/^\s+|\s+$/g, "").slice(0, 80) || "Project Style"; }
  function escapeHtml(v) { var d = document.createElement("div"); d.textContent = String(v == null ? "" : v); return d.innerHTML.replace(/"/g, "&quot;").replace(/'/g, "&#39;"); }
  function setStatus(message, type) { if (!el.mbStatus) return; el.mbStatus.textContent = message; el.mbStatus.className = "mb-status" + (type ? " " + type : ""); }
  function openOrbitDialog(options, onComplete) {
    if (typeof window.showModal !== "function") {
      setStatus("Orbit dialog service is not ready. Reopen the extension and try again.", "error");
      return;
    }
    window.showModal(options).then(function (result) {
      if (onComplete) onComplete(result);
    }).catch(function (error) {
      console.warn("Style Director dialog failed", error);
      setStatus("The dialog could not be opened.", "error");
    });
  }
  function ensureRoot() { if (!fs || !path || !storageRoot) return false; if (!fs.existsSync(storageRoot)) fs.mkdirSync(storageRoot, { recursive: true }); return true; }
  function boardDir(board) { if (!board || !/^board_[a-z0-9_]+$/i.test(board.id)) throw new Error("Invalid profile identifier."); var rootPath = path.resolve(storageRoot), resolved = path.resolve(storageRoot, board.id); if (resolved.indexOf(rootPath + path.sep) !== 0) throw new Error("Unsafe profile path."); return resolved; }
  function defaultRoles() { return { background: "#111214", surface: "#2B3130", text: "#E8E8E8", secondary: "#82918A", accent: "#FF5A36" }; }
  function migrateBoard(board) {
    board.tags = Array.isArray(board.tags) ? board.tags : [];
    board.references = Array.isArray(board.references) ? board.references : [];
    board.typography = board.typography || "Clean Sans"; board.motion = board.motion || "Smooth / Cinematic";
    board.lookIntensity = isFinite(board.lookIntensity) ? board.lookIntensity : 65;
    board.linkedStyle = board.linkedStyle !== false;
    board.colorRoles = board.colorRoles || (board.analysis && board.analysis.colorRoles) || defaultRoles();
    board.references.forEach(function (r) { r.role = /^(look|color|type|motion|layout)$/.test(r.role) ? r.role : (r.type === "font" ? "type" : r.type === "video" ? "motion" : "look"); r.included = r.included !== false; });
    return board;
  }
  function createBoard(name, selectNow) { var board = migrateBoard({ id: uid("board"), name: cleanName(name), createdAt: Date.now(), updatedAt: Date.now(), tags: [], references: [], typography: "Clean Sans", motion: "Smooth / Cinematic", analysis: null }); state.boards.push(board); if (selectNow !== false || !state.activeBoardId) state.activeBoardId = board.id; if (ensureRoot()) fs.mkdirSync(boardDir(board), { recursive: true }); saveState(); return board; }
  function saveState() { if (!ensureRoot()) return; state.schema = 2; var temp = indexPath + ".tmp"; fs.writeFileSync(temp, JSON.stringify(state, null, 2), "utf8"); if (fs.existsSync(indexPath)) fs.unlinkSync(indexPath); fs.renameSync(temp, indexPath); }
  function loadState() { if (!ensureRoot()) { setStatus("Style Director needs CEP file-system access.", "error"); return; } try { if (fs.existsSync(indexPath)) state = JSON.parse(fs.readFileSync(indexPath, "utf8")); } catch (e) { state = { schema: 2, activeBoardId: "", boards: [] }; setStatus("The old profile index was unreadable; a fresh workspace was created.", "error"); } if (!state || !Array.isArray(state.boards)) state = { schema: 2, activeBoardId: "", boards: [] }; state.boards.forEach(migrateBoard); if (!state.boards.length) createBoard("Current Project Style", false); if (!getBoard(state.activeBoardId)) state.activeBoardId = state.boards[0].id; saveState(); }
  function getBoard(id) { for (var i = 0; i < state.boards.length; i++) if (state.boards[i].id === id) return state.boards[i]; return null; }
  function currentBoard() { return getBoard(state.activeBoardId); }
  function fileUrl(p) { return encodeURI("file:///" + String(p || "").replace(/\\/g, "/")).replace(/#/g, "%23"); }
  function referenceType(p) { var ext = path.extname(p).toLowerCase(); if (/\.(mp4|mov|webm|m4v|avi)$/.test(ext)) return "video"; if (ext === ".gif") return "gif"; if (/\.(ttf|otf|woff|woff2)$/.test(ext)) return "font"; return "image"; }
  function uniqueDestination(board, source) { var dir = boardDir(board), base = cleanName(path.basename(source)), ext = path.extname(base), stem = path.basename(base, ext), dest = path.join(dir, stem + ext), n = 2; while (fs.existsSync(dest)) dest = path.join(dir, stem + "_" + n++ + ext); return dest; }
  function addStoredReference(board, storedPath, title, type) { type = type || referenceType(storedPath); board.references.push({ id: uid("ref"), type: type, role: type === "font" ? "type" : type === "video" ? "motion" : "look", included: true, title: title || path.basename(storedPath), path: storedPath, addedAt: Date.now(), palette: [], metrics: null }); }
  function addFiles(list) { var board = currentBoard(); if (!board) return; var files = Array.prototype.slice.call(list || []).filter(function (f) { return f && f.path && fs.existsSync(f.path); }); if (!files.length) { setStatus("No supported local files were found.", "error"); return; } files.forEach(function (file) { try { var destination = uniqueDestination(board, file.path); fs.copyFileSync(file.path, destination); addStoredReference(board, destination, path.basename(file.path)); } catch (e) { console.warn("Style reference import failed", e); } }); board.updatedAt = Date.now(); saveState(); render(); analyzeBoard(true); }
  function addTextReference(type) {
    var board = currentBoard();
    if (!board) return;
    var isLink = type === "link";
    openOrbitDialog({
      title: isLink ? "Add Reference Link" : "Add Style Note",
      message: isLink ? "Paste a complete webpage or inspiration URL." : "Add a short creative direction note to this Style Profile.",
      input: true,
      placeholder: isLink ? "https://example.com/reference" : "e.g. Dark, restrained, premium motion",
      defaultValue: "",
      okText: isLink ? "Add Link" : "Add Note",
      cancelText: "Cancel"
    }, function (value) {
      if (value === null) return;
      value = String(value || "").replace(/^\s+|\s+$/g, "");
      if (!value) { setStatus(isLink ? "Enter a reference URL." : "Enter a style note.", "error"); return; }
      if (isLink && !/^https?:\/\//i.test(value)) { setStatus("Use a complete http:// or https:// URL.", "error"); return; }
      board.references.push({ id: uid("ref"), type: type, role: "layout", included: true, title: isLink ? value.replace(/^https?:\/\//i, "").slice(0, 60) : value.slice(0, 60), url: isLink ? value : "", note: isLink ? "" : value, addedAt: Date.now(), palette: [], metrics: null });
      board.updatedAt = Date.now();
      saveState(); render();
      setStatus(isLink ? "Reference link added." : "Style note added.", "success");
    });
  }
  function removeReference(id) { var board = currentBoard(), index = -1; if (!board) return; for (var i = 0; i < board.references.length; i++) if (board.references[i].id === id) { index = i; break; } if (index < 0) return; var ref = board.references[index]; if (ref.path && fs.existsSync(ref.path)) try { var resolved = path.resolve(ref.path), safe = boardDir(board) + path.sep; if (resolved.indexOf(safe) === 0) fs.unlinkSync(resolved); } catch (e) { console.warn("Style reference cleanup failed", e); } board.references.splice(index, 1); if (activeReferenceId === id) activeReferenceId = ""; saveState(); analyzeBoard(true); }
  function openReference(ref) { try { var target = ref.url || fileUrl(ref.path); if (cs && cs.openURLInDefaultBrowser) cs.openURLInDefaultBrowser(target); else if (window.cep && window.cep.util) window.cep.util.openURLInDefaultBrowser(target); } catch (e) { setStatus("Could not open this reference.", "error"); } }
  function rgbHex(r,g,b) { function h(v) { var s = Math.max(0,Math.min(255,Math.round(v))).toString(16).toUpperCase(); return s.length < 2 ? "0" + s : s; } return "#" + h(r) + h(g) + h(b); }
  function hexRgb(hex) { var n = parseInt(String(hex).replace("#",""),16); return [(n>>16)&255,(n>>8)&255,n&255]; }
  function luminance(hex) { var c=hexRgb(hex); return (.2126*c[0]+.7152*c[1]+.0722*c[2])/255; }
  function saturation(hex) { var c=hexRgb(hex), max=Math.max(c[0],c[1],c[2]), min=Math.min(c[0],c[1],c[2]); return max ? (max-min)/max : 0; }
  function colorDistance(a,b) { var x=hexRgb(a), y=hexRgb(b), dr=x[0]-y[0], dg=x[1]-y[1], db=x[2]-y[2]; return Math.sqrt(dr*dr+dg*dg+db*db); }
  function analyzePixels(data,w,h) { var buckets={}, count=0, lum=0, lumSq=0, sat=0, warm=0, texture=0, neighbors=0; for(var y=0;y<h;y+=2) for(var x=0;x<w;x+=2){var i=(y*w+x)*4;if(data[i+3]<80)continue;var r=data[i],g=data[i+1],b=data[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),l=(.2126*r+.7152*g+.0722*b)/255;lum+=l;lumSq+=l*l;sat+=mx?(mx-mn)/mx:0;warm+=(r-b)/255;count++;var key=(Math.round(r/24)*24)+","+(Math.round(g/24)*24)+","+(Math.round(b/24)*24);buckets[key]=(buckets[key]||0)+1;if(x>=2){var p=i-8;texture+=(Math.abs(r-data[p])+Math.abs(g-data[p+1])+Math.abs(b-data[p+2]))/(3*255);neighbors++;}} if(!count)throw new Error("No visible pixels."); var colors=Object.keys(buckets).sort(function(a,b){return buckets[b]-buckets[a];}).map(function(k){var c=k.split(",");return rgbHex(Math.min(255,+c[0]),Math.min(255,+c[1]),Math.min(255,+c[2]));}), distinct=[]; for(var j=0;j<colors.length&&distinct.length<7;j++){var far=true;for(var d=0;d<distinct.length;d++)if(colorDistance(colors[j],distinct[d])<45){far=false;break;}if(far)distinct.push(colors[j]);} var mean=lum/count; return {palette:distinct,metrics:{luminance:mean,contrast:Math.sqrt(Math.max(0,lumSq/count-mean*mean)),saturation:sat/count,warmth:warm/count,grain:neighbors?texture/neighbors:0}}; }
  function canvasAnalysis(source,w,h) { var max=180,scale=Math.min(1,max/Math.max(w,h)),cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale)),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=cw;canvas.height=ch;ctx.drawImage(source,0,0,cw,ch);return analyzePixels(ctx.getImageData(0,0,cw,ch).data,cw,ch); }
  function mergeSamples(samples) { var metrics={luminance:0,contrast:0,saturation:0,warmth:0,grain:0},colors=[];samples.forEach(function(s){Object.keys(metrics).forEach(function(k){metrics[k]+=s.metrics[k]||0;});colors=colors.concat(s.palette||[]);});Object.keys(metrics).forEach(function(k){metrics[k]/=Math.max(1,samples.length);});var distinct=[];colors.forEach(function(c){if(distinct.length>=7)return;for(var i=0;i<distinct.length;i++)if(colorDistance(c,distinct[i])<45)return;distinct.push(c);});return {palette:distinct,metrics:metrics}; }
  function analyzeReference(ref) { return new Promise(function(resolve){ if(!ref.path||["image","gif","video"].indexOf(ref.type)<0){resolve(null);return;} if(ref.type!=="video"){var img=new Image();img.onload=function(){try{resolve(canvasAnalysis(img,img.naturalWidth,img.naturalHeight));}catch(e){resolve(null);}};img.onerror=function(){resolve(null);};img.src=fileUrl(ref.path);return;} var video=document.createElement("video"),samples=[],points=[],point=0,finished=false;video.muted=true;video.preload="metadata";function done(){if(finished)return;finished=true;resolve(samples.length?mergeSamples(samples):null);}function capture(){try{samples.push(canvasAnalysis(video,video.videoWidth,video.videoHeight));}catch(e){console.warn("Video reference sample failed",e);}point++;if(point>=points.length){done();return;}try{video.currentTime=points[point];}catch(e2){done();}}video.onloadedmetadata=function(){var duration=isFinite(video.duration)?video.duration:1;points=[.08,.28,.5,.72,.92].map(function(v){return Math.max(0,Math.min(duration-.02,duration*v));});try{video.currentTime=points[0];}catch(e){done();}};video.onseeked=capture;video.onerror=done;video.src=fileUrl(ref.path); }); }
  function semanticRoles(colors) { colors=(colors||[]).slice(0); ["#111214","#2B3130","#E8E8E8","#82918A","#FF5A36"].forEach(function(c){if(colors.indexOf(c)<0)colors.push(c);}); var byLight=colors.slice(0).sort(function(a,b){return luminance(a)-luminance(b);}), byAccent=colors.slice(0).sort(function(a,b){return saturation(b)-saturation(a);}), accent=byAccent[0], background=byLight[0], text=byLight[byLight.length-1], surface=byLight[Math.min(1,byLight.length-1)], secondary=byLight[Math.max(0,byLight.length-2)]; if(colorDistance(accent,background)<25||colorDistance(accent,text)<25)accent=byAccent[1]||"#FF5A36"; return {background:background,surface:surface,text:text,secondary:secondary,accent:accent}; }
  function aggregateAnalysis(board) { var visual=board.references.filter(function(r){return r.included!==false&&r.metrics&&r.palette&&r.palette.length;}), colorRefs=visual.filter(function(r){return r.role==="color"||r.role==="look";}), metricRefs=visual.filter(function(r){return r.role==="look"||r.role==="motion";}), metrics={luminance:0,contrast:0,saturation:0,warmth:0,grain:0},colors=[]; if(!colorRefs.length)colorRefs=visual;if(!metricRefs.length)metricRefs=visual;metricRefs.forEach(function(r){Object.keys(metrics).forEach(function(k){metrics[k]+=Number(r.metrics[k])||0;});});if(metricRefs.length)Object.keys(metrics).forEach(function(k){metrics[k]/=metricRefs.length;});colorRefs.forEach(function(r){colors=colors.concat(r.palette);});var distinct=[];colors.forEach(function(c){if(distinct.length>=7)return;for(var i=0;i<distinct.length;i++)if(colorDistance(c,distinct[i])<48)return;distinct.push(c);});["#111214","#E8E8E8","#FF5A36","#82918A","#2B3130"].forEach(function(c){if(distinct.length<5)distinct.push(c);});var dna=[], editing=[],motion=board.motion||"Smooth / Cinematic";function add(v){if(dna.indexOf(v)<0)dna.push(v);}if(metrics.luminance<.38)add("Dark");else if(metrics.luminance>.68)add("Bright");if(metrics.contrast>.22)add("High Contrast");else if(metrics.contrast<.13)add("Soft Contrast");if(metrics.saturation<.27)add("Muted");else if(metrics.saturation>.52)add("Vibrant");if(metrics.warmth>.045)add("Warm");else if(metrics.warmth<-.045)add("Cool");board.tags.forEach(add);if(board.tags.indexOf("Fast Pace")>=0){motion="Fast / Punchy";editing=["Quick Cuts","Punch-in","Speed Ramp"];}else if(board.tags.indexOf("Luxury")>=0){motion="Smooth / Cinematic";editing=["Slow Push","Match Cuts","Soft Dissolve"];}else if(board.tags.indexOf("UGC")>=0){motion="Handheld / UGC";editing=["Jump Cuts","Punch-in","Handheld"];}else if(board.tags.indexOf("Minimal")>=0){motion="Minimal / Clean";editing=["Clean Cuts","Hold Frames","Subtle Reveal"];}else editing=motion.indexOf("Fast")>=0?["Quick Cuts","Punch-in"]:["Match Cuts","Smooth Reveal"];return {palette:distinct.slice(0,5),colorRoles:semanticRoles(distinct),metrics:metrics,styleDna:dna.slice(0,7),typography:board.typography,motion:motion,editing:editing.join(" · "),analyzedAt:Date.now(),visualCount:visual.length,videoCount:visual.filter(function(r){return r.type==="video";}).length}; }
  function analyzeBoard(silent) { var board=currentBoard();if(!board)return Promise.resolve();if(!silent)setStatus("Analyzing role-aware references locally...");var targets=board.references.filter(function(r){return r.included!==false&&r.path&&["image","gif","video"].indexOf(r.type)>=0;});return Promise.all(targets.map(function(r){return analyzeReference(r).then(function(result){if(result){r.palette=result.palette;r.metrics=result.metrics;}});})).then(function(){board.analysis=aggregateAnalysis(board);board.colorRoles=board.analysis.colorRoles;board.motion=board.analysis.motion;board.updatedAt=Date.now();saveState();render();if(!silent)setStatus(board.analysis.visualCount?"Style Profile updated from "+board.analysis.visualCount+" visual reference(s).":"Add an image, GIF or video reference.",board.analysis.visualCount?"success":"error");}); }
  function metricLabel(v,low,high,a,b,c){return v<low?a:(v>high?c:b);}
  function renderSemantic(board) { if(!el.mbSemanticPalette)return;var roles=board&&board.colorRoles?board.colorRoles:defaultRoles(),labels={background:"BG",surface:"SURFACE",text:"TEXT",secondary:"SECONDARY",accent:"ACCENT"};el.mbSemanticPalette.innerHTML="";["background","surface","text","secondary","accent"].forEach(function(key){var card=document.createElement("div");card.className="mb-semantic-color";card.innerHTML='<button type="button" style="background:'+escapeHtml(roles[key])+'" title="Copy '+escapeHtml(roles[key])+'"></button><span>'+labels[key]+'</span><b>'+escapeHtml(roles[key])+'</b>';card.querySelector("button").addEventListener("click",function(){try{navigator.clipboard.writeText(roles[key]);}catch(e){console.warn("Clipboard unavailable",e);}setStatus(labels[key]+" "+roles[key]+" copied.","success");});el.mbSemanticPalette.appendChild(card);}); }
  function renderAnalysis(board){var a=board&&board.analysis;el.mbStyleDna.innerHTML="";el.mbPalette.innerHTML="";renderSemantic(board);if(!a){el.mbStyleDna.textContent="Analyze references to create a Style Profile.";["#111214","#E8E8E8","#FF5A36"].forEach(function(c){var s=document.createElement("button");s.style.background=c;el.mbPalette.appendChild(s);});[el.mbContrast,el.mbTemperature,el.mbSaturation,el.mbGrain].forEach(function(n){n.textContent="—";});el.mbEditing.textContent="—";return;}a.styleDna.forEach(function(tag){var s=document.createElement("span");s.textContent=tag;el.mbStyleDna.appendChild(s);});a.palette.forEach(function(color){var b=document.createElement("button");b.style.background=color;b.title=color;b.addEventListener("click",function(){try{navigator.clipboard.writeText(color);}catch(e){console.warn("Clipboard unavailable",e);}setStatus(color+" copied.","success");});el.mbPalette.appendChild(b);});el.mbTypography.value=board.typography||a.typography;el.mbMotion.value=board.motion||a.motion;el.mbEditing.textContent=a.editing+(a.videoCount?" · "+a.videoCount+" video sampled":"");el.mbContrast.textContent=metricLabel(a.metrics.contrast,.13,.22,"Low","Medium","High");el.mbTemperature.textContent=metricLabel(a.metrics.warmth,-.045,.045,"Cool","Neutral","Warm");el.mbSaturation.textContent=metricLabel(a.metrics.saturation,.27,.52,"Low","Balanced","High");el.mbGrain.textContent=metricLabel(a.metrics.grain,.055,.115,"Low","Medium","High");}
  function refCard(ref){var article=document.createElement("article");article.className="mb-ref"+(activeReferenceId===ref.id?" selected":"")+(ref.included===false?" excluded":"");article.dataset.referenceId=ref.id;var media="";if(ref.type==="image"||ref.type==="gif")media='<img src="'+escapeHtml(fileUrl(ref.path))+'" alt=""/>';else if(ref.type==="video")media='<video src="'+escapeHtml(fileUrl(ref.path))+'" muted loop preload="metadata"></video>';else media='<div class="mb-ref-placeholder">'+escapeHtml(ref.note||ref.url||ref.title)+"</div>";var mini=ref.palette&&ref.palette.length?'<div class="mb-ref-palette">'+ref.palette.slice(0,4).map(function(c){return '<i style="background:'+c+'"></i>';}).join("")+"</div>":"";article.innerHTML='<div class="mb-ref-media">'+media+mini+'<div class="mb-ref-actions"><button data-mb-action="preview">PREVIEW</button><button data-mb-action="analyze">SELECT</button><button class="danger" data-mb-action="remove">REMOVE</button></div></div><div class="mb-ref-meta"><strong title="'+escapeHtml(ref.title)+'">'+escapeHtml(ref.title)+'</strong><span>'+escapeHtml(ref.type)+'</span></div><div class="mb-ref-role"><label>ROLE</label><select aria-label="Reference role"><option value="look">Look</option><option value="color">Color</option><option value="type">Type</option><option value="motion">Motion</option><option value="layout">Layout</option></select><button type="button" title="Include or exclude this reference">'+(ref.included===false?"OFF":"ON")+'</button></div>';var select=article.querySelector("select"),toggle=article.querySelector(".mb-ref-role button");select.value=ref.role||"look";select.addEventListener("change",function(e){e.stopPropagation();ref.role=this.value;ref.metrics=null;saveState();analyzeBoard(true);});toggle.classList.toggle("active",ref.included===false);toggle.addEventListener("click",function(e){e.stopPropagation();ref.included=ref.included===false;saveState();analyzeBoard(true);});var video=article.querySelector("video");if(video){article.addEventListener("mouseenter",function(){var p=video.play();if(p&&p.catch)p.catch(function(error){console.warn("Reference preview unavailable",error);});});article.addEventListener("mouseleave",function(){video.pause();video.currentTime=0;});}article.addEventListener("click",function(event){var button=event.target.closest("[data-mb-action]"),action=button&&button.getAttribute("data-mb-action");if(!action)return;if(action==="preview")openReference(ref);else if(action==="remove")removeReference(ref.id);else{activeReferenceId=ref.id;render();setStatus("Reference selected for Look Match.","success");}});return article;}
  function render(){var board=currentBoard();el.mbBoardSelect.innerHTML="";state.boards.forEach(function(b){var o=document.createElement("option");o.value=b.id;o.textContent=b.name;o.selected=b.id===state.activeBoardId;el.mbBoardSelect.appendChild(o);});el.mbReferenceGrid.innerHTML="";var refs=board?board.references:[],shown=refs.filter(function(r){return roleFilter==="all"||r.role===roleFilter;});shown.forEach(function(r){el.mbReferenceGrid.appendChild(refCard(r));});el.mbReferenceCount.textContent=refs.length+" item"+(refs.length===1?"":"s");el.mbEmptyState.style.display=shown.length?"none":"block";Array.prototype.forEach.call(el.mbTagList.querySelectorAll("[data-mb-tag]"),function(button){button.classList.toggle("active",!!board&&board.tags.indexOf(button.getAttribute("data-mb-tag"))>=0);});if(el.mbRoleFilter)Array.prototype.forEach.call(el.mbRoleFilter.querySelectorAll("[data-mb-role-filter]"),function(b){b.classList.toggle("active",b.getAttribute("data-mb-role-filter")===roleFilter);});if(board){el.mbTypography.value=board.typography;el.mbMotion.value=board.motion;el.mbLinkedStyle.checked=board.linkedStyle!==false;el.mbLookIntensity.value=board.lookIntensity;el.mbLookIntensityValue.textContent=board.lookIntensity+"%";}renderAnalysis(board);}
  function payloadFor(reference,mode){var board=currentBoard(),analysis=board.analysis?JSON.parse(JSON.stringify(board.analysis)):aggregateAnalysis(board);if(reference&&reference.metrics){analysis.palette=reference.palette.slice(0,5);analysis.colorRoles=semanticRoles(analysis.palette);analysis.metrics=reference.metrics;}return{boardId:board.id,boardName:board.name,palette:analysis.palette,colorRoles:board.colorRoles||analysis.colorRoles||semanticRoles(analysis.palette),metrics:analysis.metrics,styleDna:analysis.styleDna,typography:board.typography,motion:board.motion,editing:analysis.editing,mode:mode||"all",linked:board.linkedStyle!==false,intensity:board.lookIntensity};}
  function hostAction(name,payload,busy,done){if(!bridge){setStatus("After Effects host bridge is not ready.","error");return;}setStatus(busy);bridge.call(name+"("+bridge.arg(JSON.stringify(payload))+ ")",function(result){setStatus((result&&result.message)||"Action complete.",result&&result.success?"success":"error");if(done)done(result);},120000);}
  function applyMode(mode){var board=currentBoard();if(!board)return;if(mode==="look"){createLook();return;}hostAction("ae_moodboardApplyStyle",payloadFor(null,mode),"Applying "+mode+" profile to selected layers...");}
  function createLook(){var board=currentBoard(),selected=null;if(activeReferenceId)for(var i=0;i<board.references.length;i++)if(board.references[i].id===activeReferenceId)selected=board.references[i];hostAction("ae_moodboardCreateLook",payloadFor(selected,"look"),selected?"Updating Look from selected reference...":"Creating or updating project Look...");}
  el.mbBoardSelect.addEventListener("change",function(){state.activeBoardId=this.value;activeReferenceId="";saveState();render();});
  el.mbNewBoard.addEventListener("click",function(){
    openOrbitDialog({ title:"Create Style Profile", message:"Create a focused visual direction for this project.", input:true, placeholder:"e.g. Luxury Property Launch", defaultValue:"Untitled Project Style", okText:"Create Profile", cancelText:"Cancel" },function(n){
      if(n===null)return;
      n=String(n||"").replace(/^\s+|\s+$/g,"");
      if(!n){setStatus("Enter a Style Profile name.","error");return;}
      createBoard(n,true);render();setStatus("Project Style created.","success");
    });
  });
  el.mbRenameBoard.addEventListener("click",function(){
    var b=currentBoard();if(!b)return;
    openOrbitDialog({ title:"Rename Style Profile", message:"Choose a clear name that identifies this project's visual direction.", input:true, placeholder:"Style Profile name", defaultValue:b.name, okText:"Save Name", cancelText:"Cancel" },function(n){
      if(n===null)return;
      n=String(n||"").replace(/^\s+|\s+$/g,"");
      if(!n){setStatus("Enter a Style Profile name.","error");return;}
      b.name=cleanName(n);b.updatedAt=Date.now();saveState();render();setStatus("Style Profile renamed.","success");
    });
  });
  el.mbDeleteBoard.addEventListener("click",function(){
    var b=currentBoard();if(!b)return;
    openOrbitDialog({ title:"Delete Style Profile?", message:'"'+b.name+'" and its copied references will be permanently removed.', okText:"Delete Profile", cancelText:"Keep Profile", danger:true },function(approved){
      if(!approved)return;
      try{var dir=boardDir(b);if(fs.existsSync(dir)){if(fs.rmSync)fs.rmSync(dir,{recursive:true,force:true});else fs.rmdirSync(dir,{recursive:true});}}catch(e){console.warn("Style profile folder cleanup failed",e);}
      state.boards=state.boards.filter(function(x){return x.id!==b.id;});if(!state.boards.length)createBoard("Current Project Style",true);state.activeBoardId=state.boards[0].id;saveState();render();setStatus("Style Profile deleted.","success");
    });
  });
  el.mbRevealFolder.addEventListener("click",function(){try{if(cs)cs.openURLInDefaultBrowser(fileUrl(storageRoot));}catch(e){setStatus(storageRoot,"success");}});
  el.mbBrowseReferences.addEventListener("click",function(){el.mbReferenceInput.click();});el.mbDropzone.addEventListener("click",function(){el.mbReferenceInput.click();});el.mbDropzone.addEventListener("keypress",function(e){if(e.key==="Enter"||e.key===" ")el.mbReferenceInput.click();});el.mbReferenceInput.addEventListener("change",function(){addFiles(this.files);this.value="";});
  ["dragenter","dragover"].forEach(function(name){el.mbDropzone.addEventListener(name,function(e){e.preventDefault();el.mbDropzone.classList.add("dragover");});});["dragleave","drop"].forEach(function(name){el.mbDropzone.addEventListener(name,function(e){e.preventDefault();el.mbDropzone.classList.remove("dragover");if(name==="drop")addFiles(e.dataTransfer.files);});});
  el.mbCaptureComp.addEventListener("click",function(){var board=currentBoard();if(!board)return;var output=path.join(boardDir(board),"Comp_Frame_"+Date.now()+".png");hostAction("ae_moodboardCaptureFrame",{outputPath:output},"Capturing current composition frame...",function(result){if(result&&result.success&&fs.existsSync(output)){addStoredReference(board,output,path.basename(output),"image");saveState();render();analyzeBoard(true);}});});
  el.mbAddLink.addEventListener("click",function(){addTextReference("link");});el.mbAddNote.addEventListener("click",function(){addTextReference("note");});
  el.mbTagList.addEventListener("click",function(e){var button=e.target.closest("[data-mb-tag]"),board=currentBoard();if(!button||!board)return;var tag=button.getAttribute("data-mb-tag"),i=board.tags.indexOf(tag);if(i>=0)board.tags.splice(i,1);else board.tags.push(tag);board.analysis=aggregateAnalysis(board);board.colorRoles=board.analysis.colorRoles;saveState();render();});
  if(el.mbRoleFilter)el.mbRoleFilter.addEventListener("click",function(e){var b=e.target.closest("[data-mb-role-filter]");if(!b)return;roleFilter=b.getAttribute("data-mb-role-filter");render();});
  el.mbTypography.addEventListener("change",function(){var b=currentBoard();b.typography=this.value;if(b.analysis)b.analysis.typography=this.value;saveState();});el.mbMotion.addEventListener("change",function(){var b=currentBoard();b.motion=this.value;if(b.analysis)b.analysis.motion=this.value;saveState();});
  el.mbLinkedStyle.addEventListener("change",function(){var b=currentBoard();b.linkedStyle=this.checked;saveState();});el.mbLookIntensity.addEventListener("input",function(){el.mbLookIntensityValue.textContent=this.value+"%";});el.mbLookIntensity.addEventListener("change",function(){var b=currentBoard();b.lookIntensity=Number(this.value);saveState();});
  el.mbAnalyze.addEventListener("click",function(){analyzeBoard(false);});el.mbGenerateKit.addEventListener("click",function(){hostAction("ae_moodboardGenerateStyleKit",payloadFor(null,"master"),"Creating or updating linked Master Style...");});el.mbApplyStyle.addEventListener("click",function(){applyMode("all");});el.mbRestoreStyle.addEventListener("click",function(){hostAction("ae_moodboardRestoreStyle",payloadFor(null,"restore"),"Restoring selected layers...");});el.mbMatchLook.addEventListener("click",createLook);
  Array.prototype.forEach.call(root.querySelectorAll("[data-mb-apply]"),function(button){button.addEventListener("click",function(){applyMode(this.getAttribute("data-mb-apply"));});});
  el.mbScanStyle.addEventListener("click",function(){hostAction("ae_moodboardAuditStyle",payloadFor(null,"audit"),"Scanning active composition...",function(result){if(!result||!result.success)return;var d=result.data||{};el.mbHealthScore.textContent=(d.score==null?"—":d.score+"%")+" consistent";el.mbHealthSummary.innerHTML='<strong>'+Number(d.issues||0)+' issue(s)</strong> · '+Number(d.textIssues||0)+' type · '+Number(d.colorIssues||0)+' color · '+Number(d.checked||0)+' layers checked';});});
  el.mbFixStyle.addEventListener("click",function(){hostAction("ae_moodboardApplyStyle",payloadFor(null,"all"),"Normalizing selected layers...");});
  loadState();render();
})();
